### PR TITLE
RTL version

### PR DESCRIPTION
**Pull request by iPazooki**
I have add RTL version and right now just one page is compatible with RTL

### CODE REVIEW

**Comment by niilaa** [comment]
Hi Mr Pazooki
I install your version but right menu do not work for me , it means when i click on menu , sub menu don't show.
Any idea or suggestion ?
thank so much .

**Comment by iPazooki** [comment]
Hi @niilaa  
Please download last version from here [https://github.com/iPazooki/gentelella-RTL](https://github.com/iPazooki/gentelella-RTL)
I have not completely changed all pages but form menu these should be no problem !
can you  send me picture ? 
email: ipazooki@gmail.com

**Comment by niilaa** [comment]
Hi,
Thank  so much  for your on time answer.
this problem solved for me.
I have another problem one of plugin ,i don't know which , quit me from firefox.
I didn't test other browser
it's not important which version rtl or ltr ,problem is.
again , any idea or suggestion.
thank so much .

**Comment by iPazooki** [comment]
@niilaa 
wow, you mean when you browse the site you firfox will be closed !!!

**Comment by niilaa** [comment]
Yes, and this is picture .
untitled-1
 What should i do?

**Comment by iPazooki** [comment]
@niilaa 
Thanks so much for reporting this bug, I'll fix it soon and inform you as soon as possible

**Comment by iPazooki** [comment]
@mshannaq Sure, I'll pull request as soon as possible.

**Comment by niilaa** [comment]
Hi @mshannaq , 
It isn't important which version rtl or ltr the problem is.
Even on **online demo**
My friend didn't have this problem
 The details of error is (

AdapterDeviceID: 0x0416
AdapterDriverVersion: 9.18.10.3186
AdapterSubsysID: 10e91462
AdapterVendorID: 0x8086
Add-ons: %7B6AC85730-7D0F-4de0-B3FA-21142DD85326%7D:2.8.2,FirePHPExtension-Build%40firephp.org:0.7.4.1-signed.1-signed,testpilot%40labs.mozilla.com:1.2.3.4,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0,jid1-u9RbFp9JcoEGGw%40jetpack:1.2.2.1-signed.1-signed,firebug%40software.joehewitt.com:2.0.17,jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI%40jetpack:3.0.11,e10srollout%40mozilla.org:1.0,firefox%40getpocket.com:1.0.4,webcompat%40mozilla.org:1.0,helper-sig%40savefrom.net:6.57
AddonsShouldHaveBlockedE10s: 1
AppInitDLLs: nvinit.dll
AvailablePageFile: 9724555264
AvailablePhysicalMemory: 3568513024
AvailableVirtualMemory: 97775616
BIOS_Manufacturer: American Megatrends Inc.
BlockedDllList: 
BreakpadReserveAddress: 45875200
BreakpadReserveSize: 67108864
BuildID: 20160811031722
ContainsMemoryReport: 1
CrashTime: 1471149890
E10SCohort: disqualified-control
EMCheckCompatibility: true
EventLoopNestingLevel: 1
FramePoisonBase: 00000000f0de0000
FramePoisonSize: 65536
GraphicsCriticalError: |[0][GFX1]: [D2D1.1] 2Failed to create a DeviceContext, code: 0x8007000e format 0 (t=6995.16) |[31][GFX1]: [D3D11] 2 CreateTexture2D failure Size(1079,608) Code: 0x8007000e (t=7364.66) |[32][GFX1]: Failed 2 buffer db=00000000 dw=00000000 for 20, 926, 1079, 608 (t=7364.66) |[33][GFX1]: [D3D11] 2 CreateTexture2D failure Size(84,84) Code: 0x8007000e (t=7364.73) |[34][GFX1]: [D3D11] 2 CreateTexture2D failure Size(1079,608) Code: 0x8007000e (t=7366.03) |[35][GFX1]: Failed 2 buffer db=00000000 dw=00000000 for 20, 926, 1079, 608 (t=7366.03) |[36][GFX1-]: Detected rendering device reset on refresh: 4 (t=7367.32) |[37][GFX1-]: Detected rendering device reset on refresh: 4 (t=7367.36) |[38][GFX1]: Failed to create software bitmap: Size(84,84) Code: 0x8899000c (t=7367.36) |[39][GFX1]: [D3D11] 2 CreateTexture2D failure Size(1366,128) Code: 0x8007000e (t=7368.08) |[40][GFX1]: [D3D11] 2 CreateTexture2D failure Size(1349,608) Code: 0x8007000e (t=7514.72) |[41][GFX1]: Failed 2 buffer db=00000000 dw=00000000 for 0, 926, 1349, 608 (t=7514.72) |[27][GFX1]: [D2D1.1] 1Failed to create a DeviceContext, code: 0x8007000e format 1 (t=7362.68) |[28][GFX1-]: Could not borrow DrawTarget (D3D11) 1 (t=7362.68) |[29][GFX1]: [D3D11] 2 CreateTexture2D failure Size(1079,608) Code: 0x8007000e (t=7362.68) |[30][GFX1]: Failed 2 buffer db=00000000 dw=00000000 for 20, 206, 1079, 608 (t=7362.68) 
InstallTime: 1471070864
JSOutOfMemory: Recovered
Notes: AdapterVendorID: 0x8086, AdapterDeviceID: 0x0416, AdapterSubsysID: 10e91462, AdapterDriverVersion: 9.18.10.3186
Has dual GPUs. GPU #2: AdapterVendorID2: 0x10de, AdapterDeviceID2: 0x1140, AdapterSubsysID2: 10e91462, AdapterDriverVersion2: 9.18.13.1143FP(D000-L10010-W00000000-T0000) D2D1.1? DWrite? DWrite+ D2D1.1+ D3D11 Layers? D3D11 Layers+ WebGL? EGL? EGL+ GL Context? GL Context+ WebGL+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: beta
SafeMode: 0
SecondsSinceLastCrash: 72841
StartupTime: 1471146808
SystemMemoryUsePercentage: 58
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86","buildId":"20160811031722","version":"49.0","vendor":"Mozilla","platformVersion":"49.0","xpcomAbi":"x86-msvc","hotfixVersion":"20160106.01"},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":8113,"virtualMaxMB":4096,"cpu":{"count":4,"cores":2,"vendor":"GenuineIntel","family":6,"model":60,"stepping":3,"l2cacheKB":256,"l3cacheKB":3072,"speedMHz":2494,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2"]},"os":{"name":"Windows_NT","version":"6.1","locale":"fa-IR","servicePackMajor":1,"servicePackMinor":0,"installYear":2014},"hdd":{"profile":{"model":"ATA WDC WD10JPVX-22J","revision":"1A01"},"binary":{"model":"ATA WDC WD10JPVX-22J","revision":"1A01"},"system":{"model":"ATA WDC WD10JPVX-22J","revision":"1A01"}},"gfx":{"D2DEnabled":true,"DWriteEnabled":true,"adapters":[{"description":"Intel(R) HD Graphics 4600","vendorID":"0x8086","deviceID":"0x0416","subsysID":"10e91462","RAM":null,"driver":"igdumdim64 igd10iumd64 igd10iumd64 igdumdim32 igd10iumd32 igd10iumd32","driverVersion":"9.18.10.3186","driverDate":"5-17-2013","GPUActive":true},{"description":"NVIDIA GeForce GT 720M","vendorID":"0x10de","deviceID":"0x1140","subsysID":"10e91462","RAM":2048,"driver":"nvd3dumx,nvwgf2umx,nvwgf2umx nvd3dum,nvwgf2um,nvwgf2um","driverVersion":"9.18.13.1143","driverDate":"3-10-2013","GPUActive":false}],"monitors":[{"screenWidth":1366,"screenHeight":768,"refreshRate":60,"pseudoDisplay":false}],"features":{"compositor":"d3d11","d3d11":{"status":"available","version":45056,"warp":false,"textureSharing":true,"blacklisted":false},"d2d":{"status":"available","version":"1.1"}}},"isWow64":true},"settings":{"blocklistEnabled":true,"e10sEnabled":false,"e10sCohort":"disqualified-control","telemetryEnabled":true,"locale":"en-US","update":{"channel":"beta","enabled":true,"autoDownload":true},"userPrefs":{"browser.cache.disk.capacity":358400,"browser.newtabpage.enhanced":true,"browser.urlbar.suggest.searches":true,"browser.urlbar.userMadeSearchSuggestionsChoice":true},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true},"profile":{"creationDate":16196},"addons":{"activeAddons":{"{6AC85730-7D0F-4de0-B3FA-21142DD85326}":{"blocklisted":false,"description":"Advanced Eyedropper, ColorPicker, Page Zoomer and other colorful goodies","name":"ColorZilla","userDisabled":false,"appDisabled":false,"version":"2.8.2","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16682,"updateDay":16682,"signedState":2,"isSystem":false},"FirePHPExtension-Build@firephp.org":{"blocklisted":false,"description":"Firebug Extension for PHP based AJAX Development","name":"FirePHP","userDisabled":false,"appDisabled":false,"version":"0.7.4.1-signed.1-signed","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16217,"updateDay":16920,"signedState":2,"isSystem":false},"testpilot@labs.mozilla.com":{"blocklisted":false,"description":"Help make Firefox better by running user studies.","name":"Test Pilot","userDisabled":false,"appDisabled":false,"version":"1.2.3.4","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16196,"updateDay":16921,"signedState":2,"isSystem":false},"jid1-u9RbFp9JcoEGGw@jetpack":{"blocklisted":false,"description":"A JavaScript source highlighter.","name":"JavaScript View","userDisabled":false,"appDisabled":false,"version":"1.2.2.1-signed.1-signed","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16957,"updateDay":16957,"signedState":2,"isSystem":false},"firebug@software.joehewitt.com":{"blocklisted":false,"description":"Web Development Evolved. Firebug is free and open source software distributed under the BSD License.","name":"Firebug","userDisabled":false,"appDisabled":false,"version":"2.0.17","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16217,"updateDay":16961,"signedState":2,"isSystem":false},"jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack":{"blocklisted":false,"description":"Screen capture for all or part of any web page. Add annotations, comments, blur sensitive info, and ","name":"Awesome Screenshot - Capture, Annotate & More","userDisabled":false,"appDisabled":false,"version":"3.0.11","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16853,"updateDay":16998,"signedState":2,"isSystem":false},"e10srollout@mozilla.org":{"blocklisted":false,"description":"Staged rollout of Firefox multi-process feature.","name":"Multi-process staged rollout","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16915,"updateDay":17017,"isSystem":true},"firefox@getpocket.com":{"blocklisted":false,"description":"When you find something you want to view later, put it in Pocket.","name":"Pocket","userDisabled":false,"appDisabled":false,"version":"1.0.4","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16915,"updateDay":17017,"isSystem":true},"webcompat@mozilla.org":{"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17017,"updateDay":17017,"isSystem":true},"helper-sig@savefrom.net":{"blocklisted":false,"description":"Download YouTube, VK.com and 40+ sites in one click","name":"SaveFrom.net - helper","userDisabled":false,"appDisabled":false,"version":"6.57","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16851,"updateDay":17024,"signedState":1,"isSystem":false}},"theme":{"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","blocklisted":false,"description":"The default theme.","name":"Default","userDisabled":false,"appDisabled":false,"version":"49.0","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":16196,"updateDay":17017},"activePlugins":[{"name":"Adobe Acrobat","version":"11.0.3.37","description":"Adobe PDF Plug-In For Firefox and Netscape 11.0.03","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/pdf","application/vnd.adobe.pdfxml","application/vnd.adobe.x-mars","application/vnd.fdf","application/vnd.adobe.xfdf","application/vnd.adobe.xdp+xml","application/vnd.adobe.xfd+xml"],"updateDay":15836},{"name":"Adobe Acrobat","version":"11.0.3.37","description":"Adobe PDF Plug-In For Firefox and Netscape 11.0.03","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/pdf","application/vnd.adobe.pdfxml","application/vnd.adobe.x-mars","application/vnd.fdf","application/vnd.adobe.xfdf","application/vnd.adobe.xdp+xml","application/vnd.adobe.xfd+xml"],"updateDay":15836},{"name":"Google Update","version":"1.3.31.5","description":"Google Update","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd.google.update3webcontrol.3","application/x-vnd.google.oneclickctrl.9"],"updateDay":17013},{"name":"Photo Gallery","version":"16.4.3505.912","description":"NPWLPG","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-wlpg3-detect","application/x-wlpg-detect"],"updateDay":15595},{"name":"Yahoo Application State Plugin","version":"1.0.0.7","description":"Yahoo Application State Plugin version 1.0.0.7","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd.yahoo.applicationstate"],"updateDay":15392},{"name":"","version":"3.0.72.0","description":"","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd-intel-webapi-ipt-3.0.72"],"updateDay":15751},{"name":"","version":"3.0.72.0","description":"Intel web components updater - Installs and updates the Intel web components","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd-intel-webapi-updater"],"updateDay":15751},{"name":"Shockwave Flash","version":"16.0.0.235","description":"Shockwave Flash 16.0 r0","blocklisted":false,"disabled":false,"clicktoplay":false,"mimeTypes":["application/x-shockwave-flash","application/futuresplash"],"updateDay":16482}],"activeGMPlugins":{"gmp-gmpopenh264":{"version":null,"userDisabled":false,"applyBackgroundUpdates":1},"gmp-eme-adobe":{"version":"17","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"1.4.8.903","userDisabled":false,"applyBackgroundUpdates":1}},"activeExperiment":{},"persona":null}}
Theme: classic/1.0
Throttleable: 1
TotalPageFile: 17012846592
TotalPhysicalMemory: 8507375616
TotalVirtualMemory: 4294836224
URL: http://localhost/parsagroup2/panel
UptimeTS: 7519.390307099
Vendor: Mozilla
Version: 49.0
Winsock_LSP: MSAFD Tcpip [TCP/IP] : 2 : 2 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [UDP/IP] : 2 : 2 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [RAW/IP] : 2 : 2 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [TCP/IPv6] : 2 : 23 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD Tcpip [UDP/IPv6] : 2 : 23 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD Tcpip [RAW/IPv6] : 2 : 23 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 RSVP TCPv6 Service Provider : 2 : 23 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP TCP Service Provider : 2 : 2 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP UDPv6 Service Provider : 2 : 23 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP UDP Service Provider : 2 : 2 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 MSAFD RfComm [Bluetooth] : 2 : 32 : 1 : 3 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9fc48064-7298-43e4-b7bd-181f2089792a
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.
)

**Comment by niilaa** [comment]
Hi iPazooki ,
In RTL version responsive also have problem

**Comment by iPazooki** [comment]
@niilaa 
Hi, I'm really sorry but recently I'm very busy with CRM project, I'll fix all mentioned problems as soon as possible.

**Comment by niilaa** [comment]
I solve problem firefox .
but this version isn't responsive.
tnx

**Comment by softpeterkk** [comment]
hi iPazooki: thank for your work for RTL version. but it's not  Responsive.

**Comment by AmrBerag** [comment]
Hi,
I made some changes and fixes to the custom-rtl.css 
 it is now responsive and the menus slide to the correct directions
it was simple to fix just rename the class right_col to left_col and swap left with right and vice versa and also add some text-align in CSS.
the attached file is renamed because this form doesn't accept css extension.
[custom-rtl.css.txt](https://github.com/puikinsh/gentelella/files/859787/custom-rtl.css.txt)

regards

**Pull request closed without merging**
