### PR TITLE
Update 15 redo

### PR DESCRIPTION
**Pull request by cristianraiber**

### CODE REVIEW

**Comment by britneywright** [comment]
Hi I'm interested in the 1.5 release. Is there a time you're targeting for getting it out? Any particular areas you need help with or reviews on?

**Comment by cristianraiber** [comment]
@britneywright - reviews would actually help quite a bit :) This is the PR to bump up Gentelella to v1.5 and add BS4 compatibility. Once it's merged, it wi'll in testing mode for a while and we'll ask everyone to test it as much as possible. 

Thanks,
Cristian.

**Comment by britneywright** [comment]
This is what I'm seeing currently when I load the PR.
screen shot 2019-02-25 at 12 56 09 pm

**Comment by cristianraiber** [comment]
@razvanaldea89 - see above

**Comment by razvanaldea89** [comment]
Hmmm.... looks like the old update( update-1.5 and not update-15-redo  ). Hint on how could I tell :
The old branch update-1.5 has `-->` under the name. So branch `update-15-redo` is the actual one with bootstrap 4 and bug fixing :)

**Comment by britneywright** [comment]
Ooh thanks, yeah mixed them up.

**Comment by britneywright** [comment]
ok now I seem to be having an issue with gulp. 

```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/bwrigh833/opensource/gentelella/node_modules/undertaker/lib/set-task.js:10:3)
```

Also npm is trying to move me to "browser-sync": "^2.26.3" and "gulp": "^4.0.0" any issue with that?

**Comment by cristianraiber** [comment]
@britneywright - there's a new branch called Gentella-BS4 [BETA] that you should be testing :)

**Comment by britneywright** [comment]
thanks, I've got it running now. Realized gulp version 4 doesn't play nice, so far looks good with gulp 3.9.1

**Comment by britneywright** [comment]
Is there another place to discuss the branch? One thing I want to push for is using the latest version of bootstrap, 4.3.1. I think there's a cross site scripting vulnerability with earlier versions https://snyk.io/test/npm/bootstrap/4.1.2

**Comment by cristianraiber** [comment]
@britneywright - just open up a new issue :)

**Pull request closed without merging**
